### ISSUE TITLE
Parameter settings when deleting an object

### ISSUE THREAD

**Issue by hollow1123** [buaacyw/GaussianEditor#20]
I tried this example of deleting bicycle given in the paper. 
![图片](https://github.com/buaacyw/GaussianEditor/assets/142968865/f38e3c66-6525-430f-b4c4-d99c9402c459)

The paper said: when deleting the bike directly, there are still Gaussian points around the bike which are not deleted, resulting in the creation of artifacts, so 2D inpainting optimization is needed.

Then after the optimization of deleting the bike, just like below, the optimized scene is not ideal due to the bad 2D inpainting result. (the text I used for inpainting model is "bench",which is the background description).Is this due to the fact that the results in your paper were only optimized in fewer steps?The parameter of my optimization step is the program default value.
![QQ截图20231224144656](https://github.com/buaacyw/GaussianEditor/assets/142968865/ddce47ec-06bf-4d4d-ba94-3be4a68a3b10)

**Comment by buaacyw** [comment]
Hi! The poor 2D inpainting result is caused by a too large masked.
The quality of 2D mask sent to 2D inpainting models is essential for getting a nice result.
The default setting in WebUI works nice for the removing something on tables since we dilate the mask a lot by `Mask Dilate` and `Fix Holes`.
For this bike scene, we disabled `Fix Holes` and set `Mask Dilate` and `Inpaint Scale` to a small value. 

For more details please read [hyperparameter guide](https://github.com/buaacyw/GaussianEditor/blob/master/docs/hyperparameter.md#delete)
